#!/bin/bash

set -e

SCRIPT_DIR=$(dirname $0)
PROJECT_ROOT=$(dirname $SCRIPT_DIR)

if [ -f $PROJECT_ROOT/.env ]; then
    set -o allexport
    source $PROJECT_ROOT/.env
    set +o allexport
else
    echo "No .env file found"
fi

python $PROJECT_ROOT/run_dev.py
