#!/bin/bash

set -e

SCRIPT_DIR=$(dirname $0)
PROJECT_ROOT=$(dirname $SCRIPT_DIR)

if [ -f $PROJECT_ROOT/.env ]; then
    set -o allexport
    source $PROJECT_ROOT/.env
    set +o allexport
else
    echo "No .env file found"
fi

docker build -t pwid-flask-app $PROJECT_ROOT

docker run --name pwid-flask-app -p 5000:5000 pwid-flask-app
