#!/bin/bash

set -e

SCRIPT_DIR=$(dirname $0)
PROJECT_ROOT=$(dirname $SCRIPT_DIR)

if [ -f $PROJECT_ROOT/.env ]; then
    set -o allexport
    source $PROJECT_ROOT/.env
    set +o allexport
else
    echo "No .env file found"
fi

echo "starting development server from" $PROJECT_ROOT

docker build -t pwid-flask-app $PROJECT_ROOT

docker run \
    --name pwid-flask-app \
    -v "$PROJECT_ROOT"/src:/app/src:ro \
    -e FLASK_ENV=development \
    -e FLASK_DEBUG=1 \
    -p 5000:5000 -d \
    pwid-flask-app
