#!/bin/bash

set -e

# colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NO_COLOR='\033[0m'

# subroutines
yell() {
    echo -e "$RED$0: $*$NO_COLOR" >&2
}

die() {
    yell "$*"
    exit 77
}

try() {
    "$@" || die "Error when running '$*'"
}

trycatch() {
    "$@" 2>/dev/null || cont # nevermind even if have errors
}

success() {
    echo -e "$GREEN${*:-success}$NO_COLOR"
}

warning() {
    echo -e "$YELLOW$*$NO_COLOR"
}

cont() {
    warning "Error occured but we can continue. Please re-check problems manually."
}

# static type check
echo "Installing stub packages..."
trycatch mypy dpm --install-types --non-interactive --namespace-packages
echo "Running static type check..."
try mypy dpm \
    --ignore-missing-imports \
    --disallow-untyped-defs \
    --namespace-packages \
    success

echo "Remove unused imports..."
try autoflake \
    --in-place \
    --remove-unused-variables \
    --recursive \
    src \
    tests
success

# formatting
echo "Running formatter with black..."
try black \
    -S \
    --line-length=88 \
    src tests
success

# linting
echo "Running linter with flake8..."
try flake8 src tests --max-line-length=88 --ignore=E203,W503
success

# isort
echo "Run import sorting with isort..."
try isort \
    --atomic \
    --recursive \
    --project=src \
    --section-default=THIRDPARTY \
    --multi-line=3 \
    --force-grid-wrap=0 \
    --combine-as \
    --line-width=88 \
    --trailing-comma \
    --apply \
    src \
    tests
success

# repeat static type check and linting
echo "Run mypy again..."
try mypy src \
    --ignore-missing-imports \
    --disallow-untyped-defs \
    --namespace-packages
success

echo "Running linter with flake8 again..."
try flake8 src tests --max-line-length=88 --ignore=E203,W503
success
